version: '3'
services:
  jenkins:
    image: jenkins:latest
    container_name: jenkins
    user: jenkins
    volumes:
      - jenkins_vol:/var/jenkins_home
    ports:
      - "8181:8080"
      - "50000:50000"
    #environment:
    #JENKINS_OPTS: "--prefix=/jenkins"

  nexus:
    image: sonatype/nexus
    ports:
      - "8081:8081"
    

volumes:
    jenkins_vol:
