apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-vol
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: nginx-pv-storage
        persistentVolumeClaim::
          claimName: nginx-pv-claim
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-pv-storage
          mountPath: /usr/share/nginx/html
