AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template to create Security Group
Resources:
  MySG:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupName: SampleSG
      GroupDescription: SampleSG
