# kubectl create -f jenkins-service.yml
apiVersion: v1
kind: Service
metadata:
  name: jenkins-deploy
  labels:
    app: jenkins
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30081
  selector:
    app: jenkins
