- hosts:
    - ubuntu # Make sure python avilable on target ubuntu instance, apt-get install python -y
  tasks:
    - name: ensure package cache is up to date
      apt: update_cache=yes cache_valid_time=3600
    - name: install web server
      apt: pkg=apache2 state=present
    - name: install index page
      copy: src=index.html dest=/var/www/html/index.html backup=yes
      notify: restart apache2
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
