 # Assume we have two ubuntu instances on AWS, both are connected to Ansible server.
 # Also, both are goruped under [ubuntus] in hosts/inventory file, also configred in yml file i.e., playbook as out target hosts.
 # Now, I want to run the below playbook on only on the one target instance ubuntu-1. Using limit option, we can Limit to specific hosts.
 # Command: ansible-playbook limit.yml -l ubuntu-1
 - hosts:
    - ubuntus
  tasks:
    - name: ensure package cache is up to date
      apt: update_cache=yes cache_valid_time=3600
      tags: install
    - name: install web server
      apt: pkg=apache2 state=present
      tags: install
    - name: install index page
      copy: src=index.html dest=/var/www/html/index.html backup=yes
      tags: configure
      notify: restart apache2
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
